{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "toc": true
   },
   "source": [
    "<h1>Table of Contents<span class=\"tocSkip\"></span></h1>\n",
    "<div class=\"toc\"><ul class=\"toc-item\"><li><span><a href=\"#data-mining\" data-toc-modified-id=\"data-mining-1\"><span class=\"toc-item-num\">1&nbsp;&nbsp;</span>data mining</a></span></li><li><span><a href=\"#data-exploration\" data-toc-modified-id=\"data-exploration-2\"><span class=\"toc-item-num\">2&nbsp;&nbsp;</span>data exploration</a></span></li></ul></div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import basics\n",
    "\n",
    "from google.cloud import bigquery\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "import pandas_gbq\n",
    "pd.set_option('display.max_rows', 500)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# data mining"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sql = \"\"\"\n",
    "SELECT *\n",
    "FROM\n",
    "  `bigquery-public-data.covid19_jhu_csse.confirmed_cases`\n",
    "WHERE country_region = \"US\"\n",
    "ORDER BY country_region DESC\n",
    "\"\"\"\n",
    "usa_cases = pandas_gbq.read_gbq(sql, project_id='liveramp-ts-bigquery')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "usa_cases"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# data exploration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "usa_cases.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# drop unneeded columns\n",
    "usa_cases = usa_cases.drop(['latitude', 'longitude', 'location_geom'], axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>_1_22_20</th>\n",
       "      <th>_1_23_20</th>\n",
       "      <th>_1_24_20</th>\n",
       "      <th>_1_25_20</th>\n",
       "      <th>_1_26_20</th>\n",
       "      <th>_1_27_20</th>\n",
       "      <th>_1_28_20</th>\n",
       "      <th>_1_29_20</th>\n",
       "      <th>_1_30_20</th>\n",
       "      <th>_1_31_20</th>\n",
       "      <th>...</th>\n",
       "      <th>_6_11_20</th>\n",
       "      <th>_6_12_20</th>\n",
       "      <th>_6_13_20</th>\n",
       "      <th>_6_14_20</th>\n",
       "      <th>_6_15_20</th>\n",
       "      <th>_6_16_20</th>\n",
       "      <th>_6_17_20</th>\n",
       "      <th>_6_18_20</th>\n",
       "      <th>_6_19_20</th>\n",
       "      <th>_6_20_20</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>...</td>\n",
       "      <td>2023590</td>\n",
       "      <td>2048986</td>\n",
       "      <td>2074526</td>\n",
       "      <td>2094058</td>\n",
       "      <td>2114026</td>\n",
       "      <td>2137731</td>\n",
       "      <td>2163290</td>\n",
       "      <td>2191052</td>\n",
       "      <td>2222579</td>\n",
       "      <td>2255119</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1 rows Ã— 151 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   _1_22_20  _1_23_20  _1_24_20  _1_25_20  _1_26_20  _1_27_20  _1_28_20  \\\n",
       "0         1         1         2         2         5         5         5   \n",
       "\n",
       "   _1_29_20  _1_30_20  _1_31_20  ...  _6_11_20  _6_12_20  _6_13_20  _6_14_20  \\\n",
       "0         5         5         7  ...   2023590   2048986   2074526   2094058   \n",
       "\n",
       "   _6_15_20  _6_16_20  _6_17_20  _6_18_20  _6_19_20  _6_20_20  \n",
       "0   2114026   2137731   2163290   2191052   2222579   2255119  \n",
       "\n",
       "[1 rows x 151 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "usa_cases"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122683a50> has a label of '_1_22_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122683bd0> has a label of '_1_23_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1226c1450> has a label of '_1_24_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1226c1110> has a label of '_1_25_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122683b10> has a label of '_1_26_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227086d0> has a label of '_1_27_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122708050> has a label of '_1_28_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122683a90> has a label of '_1_29_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227080d0> has a label of '_1_30_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1226c15d0> has a label of '_1_31_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122708610> has a label of '_2_1_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12271a3d0> has a label of '_2_2_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12271a050> has a label of '_2_3_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227085d0> has a label of '_2_4_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122723410> has a label of '_2_5_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122723050> has a label of '_2_6_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122708c10> has a label of '_2_7_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12272a390> has a label of '_2_8_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12272a050> has a label of '_2_9_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12272a550> has a label of '_2_10_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122733350> has a label of '_2_11_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227338d0> has a label of '_2_12_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122733410> has a label of '_2_13_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12277c2d0> has a label of '_2_14_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12277c810> has a label of '_2_15_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12277c450> has a label of '_2_16_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227971d0> has a label of '_2_17_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227977d0> has a label of '_2_18_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122797450> has a label of '_2_19_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227bc210> has a label of '_2_20_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227bc710> has a label of '_2_21_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227bc390> has a label of '_2_22_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227c41d0> has a label of '_2_23_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227c4710> has a label of '_2_24_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227c4350> has a label of '_2_25_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122876190> has a label of '_2_26_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122876650> has a label of '_2_27_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228762d0> has a label of '_2_28_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228880d0> has a label of '_2_29_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228885d0> has a label of '_3_1_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122888250> has a label of '_3_2_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228ea050> has a label of '_3_3_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228ea590> has a label of '_3_4_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228ea210> has a label of '_3_5_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1227235d0> has a label of '_3_6_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228f3550> has a label of '_3_7_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228f31d0> has a label of '_3_8_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122723990> has a label of '_3_9_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228fb550> has a label of '_3_10_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228fb190> has a label of '_3_11_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228eac50> has a label of '_3_12_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122904490> has a label of '_3_13_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122904110> has a label of '_3_14_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228ea710> has a label of '_3_15_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122932410> has a label of '_3_16_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122932050> has a label of '_3_17_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1228fbb90> has a label of '_3_18_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12293d390> has a label of '_3_19_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12293d890> has a label of '_3_20_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12293d510> has a label of '_3_21_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122945350> has a label of '_3_22_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122945810> has a label of '_3_23_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122945490> has a label of '_3_24_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12294e210> has a label of '_3_25_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12294e810> has a label of '_3_26_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12294e450> has a label of '_3_27_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122969290> has a label of '_3_28_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122969750> has a label of '_3_29_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229693d0> has a label of '_3_30_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122973210> has a label of '_3_31_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229736d0> has a label of '_4_1_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122973350> has a label of '_4_2_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12297c090> has a label of '_4_3_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12297c690> has a label of '_4_4_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12297c310> has a label of '_4_5_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12298d110> has a label of '_4_6_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12298d610> has a label of '_4_7_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x12298d290> has a label of '_4_8_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229b1050> has a label of '_4_9_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229b1590> has a label of '_4_10_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229b11d0> has a label of '_4_11_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122932550> has a label of '_4_12_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229c24d0> has a label of '_4_13_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229c2150> has a label of '_4_14_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229328d0> has a label of '_4_15_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229cb450> has a label of '_4_16_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229cb0d0> has a label of '_4_17_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229b1c50> has a label of '_4_18_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229e5410> has a label of '_4_19_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229e5090> has a label of '_4_20_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229b1710> has a label of '_4_21_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229ef390> has a label of '_4_22_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229ef050> has a label of '_4_23_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x1229ef510> has a label of '_4_24_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a09350> has a label of '_4_25_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a09890> has a label of '_4_26_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a09510> has a label of '_4_27_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a122d0> has a label of '_4_28_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a12750> has a label of '_4_29_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a12390> has a label of '_4_30_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a24290> has a label of '_5_1_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a24750> has a label of '_5_2_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a243d0> has a label of '_5_3_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a2c250> has a label of '_5_4_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a2c710> has a label of '_5_5_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a2c390> has a label of '_5_6_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a35210> has a label of '_5_7_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a35710> has a label of '_5_8_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a35350> has a label of '_5_9_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a3e190> has a label of '_5_10_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a3e710> has a label of '_5_11_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a3e350> has a label of '_5_12_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a461d0> has a label of '_5_13_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a46750> has a label of '_5_14_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a46390> has a label of '_5_15_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a4f250> has a label of '_5_16_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a4f810> has a label of '_5_17_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a4f410> has a label of '_5_18_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a572d0> has a label of '_5_19_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a57850> has a label of '_5_20_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a57450> has a label of '_5_21_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a69390> has a label of '_5_22_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a698d0> has a label of '_5_23_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a57d90> has a label of '_5_24_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a71310> has a label of '_5_25_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a71990> has a label of '_5_26_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122932ed0> has a label of '_5_27_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a79510> has a label of '_5_28_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a79110> has a label of '_5_29_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a83090> has a label of '_5_30_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a83610> has a label of '_5_31_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122a83210> has a label of '_6_1_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122ae80d0> has a label of '_6_2_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122ae8650> has a label of '_6_3_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122ae8290> has a label of '_6_4_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122af1110> has a label of '_6_5_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122af1690> has a label of '_6_6_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122af1290> has a label of '_6_7_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b03190> has a label of '_6_8_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b03710> has a label of '_6_9_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b03310> has a label of '_6_10_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b4a250> has a label of '_6_11_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b4a750> has a label of '_6_12_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b4a390> has a label of '_6_13_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b54290> has a label of '_6_14_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b54810> has a label of '_6_15_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b54410> has a label of '_6_16_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b6f390> has a label of '_6_17_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b6f890> has a label of '_6_18_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b6f4d0> has a label of '_6_19_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n",
      "/Users/aschul/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py:572: UserWarning: The handle <matplotlib.lines.Line2D object at 0x122b77390> has a label of '_6_20_20' which cannot be automatically added to the legend.\n",
      "  ax.legend(handles, labels, loc=\"best\", title=title)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.axes._subplots.AxesSubplot at 0x12263d810>"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZAAAAD4CAYAAADCb7BPAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjMsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+AADFEAAAQuElEQVR4nO3dXaxlZX3H8e+vDDC+oAzDQCmHdsY6F4VeoJwAjTeo7TCQtNCqCV6UCaWZxmrSNxOxNkHBC7SxNqSWZloJQ1NFqjVMUiydUo298IUzSnkp0jniC0cIjAylWIKK/nuxn9E9w5455zxnZu85c76fZGWv/V/Pel48Cb/Za63tTlUhSdJi/cykJyBJWp4MEElSFwNEktTFAJEkdTFAJEldVk16AuNy6qmn1vr16yc9DUlaVnbt2vXdqlo36tiKCZD169czMzMz6WlI0rKS5FsHO+YlLElSFwNEktTFAJEkdVkx90AkaaX74Q9/yNzcHM8///yLjq1evZqpqSmOP/74BfdngEjSCjE3N8dJJ53E+vXrSfKTelXx1FNPMTc3x4YNGxbcn5ewJGmFeP7551m7du1+4QGQhLVr1478ZHIoBogkrSAHhsd89UMxQCRJXQwQSVIXA0SSVpCD/Yhgz48LGiCStEKsXr2ap5566kVhse8prNWrVy+qPx/jlaQVYmpqirm5Ofbs2fOiY/u+B7IYBogkrRDHH3/8or7nMR8vYUmSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6GCCSpC4GiCSpiwEiSepigEiSuhggkqQu8wZIkrOSfDbJQ0keTPIHrX5Kkp1JdrfXNa2eJDcmmU1yX5LXDvW1pbXfnWTLUP28JPe3c25M+3X3njEkSeOxkE8gLwB/UlW/BFwIvD3J2cA1wN1VtRG4u70HuATY2LatwE0wCAPgWuAC4Hzg2n2B0NpsHTpvc6svagxJ0vjMGyBV9XhVfaXtPws8BJwJXAZsb822A5e3/cuAW2vgi8DJSc4ALgZ2VtXeqnoa2AlsbsdeUVVfqMHvLN56QF+LGUOSNCaLugeSZD3wGuBLwOlV9TgMQgY4rTU7E3h06LS5VjtUfW5EnY4xJEljsuAASfJy4FPAH1bV/x6q6YhaddQPOZ2FnJNka5KZJDOjfgNYktRvQQGS5HgG4fEPVfVPrfzEvstG7fXJVp8Dzho6fQp4bJ761Ih6zxj7qaptVTVdVdPr1q1byFIlSQu0kKewAnwUeKiq/mLo0A5g35NUW4A7hupXtielLgSeaZef7gI2JVnTbp5vAu5qx55NcmEb68oD+lrMGJKkMVm1gDavA34buD/Jva32p8ANwO1Jrga+DbylHbsTuBSYBZ4DrgKoqr1Jrgfuae2uq6q9bf9twC3AS4DPtI3FjiFJGp8MHnw69k1PT9fMzMykpyFJy0qSXVU1PeqY30SXJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSFwNEktTFAJEkdTFAJEldDBBJUhcDRJLUxQCRJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSFwNEktTFAJEkdTFAJEldDBBJUhcDRJLUxQCRJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSFwNEktTFAJEkdTFAJEldDBBJUpd5AyTJzUmeTPLAUO29Sb6T5N62XTp07N1JZpM8nOTiofrmVptNcs1QfUOSLyXZneQTSU5o9RPb+9l2fP18Y0iSxmchn0BuATaPqH+4qs5t250ASc4GrgDOaef8dZLjkhwHfAS4BDgbeGtrC/CB1tdG4Gng6la/Gni6ql4NfLi1O+gYi1u2JGmp5g2Qqvo8sHeB/V0G3FZV36+qbwCzwPltm62qR6rqB8BtwGVJArwB+GQ7fztw+VBf29v+J4E3tvYHG0OSNEZLuQfyjiT3tUtca1rtTODRoTZzrXaw+lrgf6rqhQPq+/XVjj/T2h+srxdJsjXJTJKZPXv29K1SkjRSb4DcBPwicC7wOPChVs+IttVR7+nrxcWqbVU1XVXT69atG9VEktSpK0Cq6omq+lFV/Rj4W356CWkOOGuo6RTw2CHq3wVOTrLqgPp+fbXjr2RwKe1gfUmSxqgrQJKcMfT2N4F9T2jtAK5oT1BtADYCXwbuATa2J65OYHATfEdVFfBZ4M3t/C3AHUN9bWn7bwb+vbU/2BiSpDFaNV+DJB8HLgJOTTIHXAtclORcBpeOvgn8HkBVPZjkduC/gBeAt1fVj1o/7wDuAo4Dbq6qB9sQ7wJuS/J+4KvAR1v9o8DfJ5ll8MnjivnGkCSNTwb/qD/2TU9P18zMzKSnIUnLSpJdVTU96pjfRJckdTFAJEldDBBJUhcDRJLUxQCRJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSFwNEktTFAJEkdTFAJEldDBBJUhcDRJLUxQCRJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSFwNEktTFAJEkdTFAJEldDBBJUhcDRJLUxQCRJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSl3kDJMnNSZ5M8sBQ7ZQkO5Psbq9rWj1Jbkwym+S+JK8dOmdLa787yZah+nlJ7m/n3JgkvWNIksZnIZ9AbgE2H1C7Bri7qjYCd7f3AJcAG9u2FbgJBmEAXAtcAJwPXLsvEFqbrUPnbe4ZQ5I0XvMGSFV9Hth7QPkyYHvb3w5cPlS/tQa+CJyc5AzgYmBnVe2tqqeBncDmduwVVfWFqirg1gP6WswYkqQx6r0HcnpVPQ7QXk9r9TOBR4fazbXaoepzI+o9Y7xIkq1JZpLM7NmzZ1ELlCQd2uG+iZ4Rteqo94zx4mLVtqqarqrpdevWzdOtJGkxegPkiX2Xjdrrk60+B5w11G4KeGye+tSIes8YkqQx6g2QHcC+J6m2AHcM1a9sT0pdCDzTLj/dBWxKsqbdPN8E3NWOPZvkwvb01ZUH9LWYMSRJY7RqvgZJPg5cBJyaZI7B01Q3ALcnuRr4NvCW1vxO4FJgFngOuAqgqvYmuR64p7W7rqr23Zh/G4MnvV4CfKZtLHYMSdJ4ZfDw07Fvenq6ZmZmJj0NSVpWkuyqqulRx/wmuiSpiwEiSepigEiSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6GCCSpC4GiCSpiwEiSepigEiSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6GCCSpC4GiCSpiwEiSepigEiSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6LClAknwzyf1J7k0y02qnJNmZZHd7XdPqSXJjktkk9yV57VA/W1r73Um2DNXPa/3PtnNzqDEkSeNzOD6BvL6qzq2q6fb+GuDuqtoI3N3eA1wCbGzbVuAmGIQBcC1wAXA+cO1QINzU2u47b/M8Y0iSxuRIXMK6DNje9rcDlw/Vb62BLwInJzkDuBjYWVV7q+ppYCewuR17RVV9oaoKuPWAvkaNIUkak6UGSAH/mmRXkq2tdnpVPQ7QXk9r9TOBR4fOnWu1Q9XnRtQPNcZ+kmxNMpNkZs+ePZ1LlCSNsmqJ57+uqh5LchqwM8nXDtE2I2rVUV+wqtoGbAOYnp5e1LmSpENb0ieQqnqsvT4JfJrBPYwn2uUn2uuTrfkccNbQ6VPAY/PUp0bUOcQYkqQx6Q6QJC9LctK+fWAT8ACwA9j3JNUW4I62vwO4sj2NdSHwTLv8dBewKcmadvN8E3BXO/Zskgvb01dXHtDXqDEkSWOylEtYpwOfbk/WrgI+VlX/kuQe4PYkVwPfBt7S2t8JXArMAs8BVwFU1d4k1wP3tHbXVdXetv824BbgJcBn2gZww0HGkCSNSQYPOB37pqena2ZmZtLTkKRlJcmuoa9p7MdvokuSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6GCCSpC4GiCSpiwEiSepigEiSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6GCCSpC4GiCSpiwEiSepigEiSuhggkqQuBogkqYsBIknqYoBIkroYIJKkLgaIJKmLASJJ6mKASJK6GCCSpC4GiCSpy7IOkCSbkzycZDbJNZOejyStJMs2QJIcB3wEuAQ4G3hrkrMnOytJWjmWbYAA5wOzVfVIVf0AuA24bMJzkqQVYzkHyJnAo0Pv51rtJ5JsTTKTZGbPnj1jnZwkHeuWc4BkRK32e1O1raqmq2p63bp1Y5qWJK0MyzlA5oCzht5PAY9NaC6StOIs5wC5B9iYZEOSE4ArgB0TnpMkrRirJj2BXlX1QpJ3AHcBxwE3V9WDE56WJK0YyzZAAKrqTuDOSc9Dklai5XwJS5I0QQaIJKmLASJJ6mKASJK6pKrmb3UMSLIH+Nak59HhVOC7k57EmLnmY99KWy8s3zX/QlWN/Cb2igmQ5SrJTFVNT3oe4+Saj30rbb1wbK7ZS1iSpC4GiCSpiwFy9Ns26QlMgGs+9q209cIxuGbvgUiSuvgJRJLUxQCRJHUxQI4CSU5JsjPJ7va65iDttrQ2u5NsGXF8R5IHjvyMl24pa07y0iT/nORrSR5McsN4Z79wSTYneTjJbJJrRhw/Mckn2vEvJVk/dOzdrf5wkovHOe+l6F1zkl9LsivJ/e31DeOee6+l/J3b8Z9P8r0k7xzXnA+LqnKb8AZ8ELim7V8DfGBEm1OAR9rrmra/Zuj4bwEfAx6Y9HqO9JqBlwKvb21OAP4DuGTSaxox/+OArwOvavP8T+DsA9r8PvA3bf8K4BNt/+zW/kRgQ+vnuEmv6Qiv+TXAz7X9Xwa+M+n1HOk1Dx3/FPCPwDsnvZ7FbH4COTpcBmxv+9uBy0e0uRjYWVV7q+ppYCewGSDJy4E/Bt4/hrkeLt1rrqrnquqzAFX1A+ArDH6R8mhzPjBbVY+0ed7GYN3Dhv93+CTwxiRp9duq6vtV9Q1gtvV3tOtec1V9tar2/arog8DqJCeOZdZLs5S/M0kuZ/CPo2X3e0YGyNHh9Kp6HKC9njaizZnAo0Pv51oN4HrgQ8BzR3KSh9lS1wxAkpOBXwfuPkLzXIp55z/cpqpeAJ4B1i7w3KPRUtY87E3AV6vq+0donodT95qTvAx4F/C+MczzsFvWPyi1nCT5N+BnRxx6z0K7GFGrJOcCr66qPzrwuuqkHak1D/W/Cvg4cGNVPbL4GR5xh5z/PG0Wcu7RaClrHhxMzgE+AGw6jPM6kpay5vcBH66q77UPJMuKATImVfWrBzuW5IkkZ1TV40nOAJ4c0WwOuGjo/RTwOeBXgPOSfJPB3/O0JJ+rqouYsCO45n22Abur6i8Pw3SPhDngrKH3U8BjB2kz1wLxlcDeBZ57NFrKmkkyBXwauLKqvn7kp3tYLGXNFwBvTvJB4GTgx0mer6q/OvLTPgwmfRPGrQD+nP1vKH9wRJtTgG8wuIm8pu2fckCb9Syfm+hLWjOD+z2fAn5m0ms5xBpXMbi2vYGf3lw954A2b2f/m6u3t/1z2P8m+iMsj5voS1nzya39mya9jnGt+YA272WZ3USf+ATcCgbXf+8GdrfXff+RnAb+bqjd7zC4mToLXDWin+UUIN1rZvAvvAIeAu5t2+9Oek0HWeelwH8zeErnPa12HfAbbX81g6dvZoEvA68aOvc97byHOQqfMjvcawb+DPi/ob/pvcBpk17Pkf47D/Wx7ALE/ysTSVIXn8KSJHUxQCRJXQwQSVIXA0SS1MUAkSR1MUAkSV0MEElSl/8HmUffF63TDVgAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "usa_cases.plot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": true,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": true
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
